"""add user

Revision ID: 2637339545fc
Revises: 448eb312800a
Create Date: 2025-12-22 20:24:43.246823

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2637339545fc"
down_revision: str | Sequence[str] | None = "448eb312800a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("revoked_tokens", "is_refresh")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revoked_tokens",
        sa.Column(
            "is_refresh", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
