"""add user

Revision ID: 74f3276a7b87
Revises: 08520830cddc
Create Date: 2025-12-27 15:06:45.335716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f3276a7b87'
down_revision: Union[str, Sequence[str], None] = '08520830cddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(
        op.f('user_email_key'),
        'user',
        ['email'],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
