"""add user

Revision ID: 781e386f2232
Revises: 2637339545fc
Create Date: 2025-12-22 20:31:20.167930

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "781e386f2232"
down_revision: str | Sequence[str] | None = "2637339545fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "revoked_tokens", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "revoked_tokens", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "revoked_tokens", type_="foreignkey")
    op.drop_column("revoked_tokens", "user_id")
    # ### end Alembic commands ###
