"""add user

Revision ID: a1a1ec2ea7ef
Revises: f073201d25d2
Create Date: 2025-12-18 15:40:09.256001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1a1ec2ea7ef"
down_revision: str | Sequence[str] | None = "f073201d25d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "phone_number",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "phone_number",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    # ### end Alembic commands ###
