"""add quantity to product

Revision ID: add_quantity_to_product
Revises: 6aa53aaed419
Create Date: 2026-01-13 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_quantity_to_product'
down_revision: Union[str, Sequence[str], None] = '6aa53aaed419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'product',
        sa.Column(
            'quantity', sa.Integer(), nullable=False, server_default='0'
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
